base: 'example/config/base.yaml'
prompts:
- - 1girl smiling
  - 1girl open mouth 
  - 1girl crying, pout
n_prompt: 
  - 'wrong white balance, dark, sketches,worst quality,low quality, deformed, distorted, disfigured, bad eyes, wrong lips,weird mouth, bad teeth, mutated hands and fingers, bad anatomy,wrong anatomy, amputation, extra limb, missing limb, floating,limbs, disconnected limbs, mutation, ugly, disgusting, bad_pictures, negative_hand-neg'
validation_data:
  input_name: 'anya'
  validation_input_path: 'example/img'
  save_path: 'example/result'
  mask_sim_range: [-1]
generate:
  use_lora: false
  use_db: true 
  global_seed: 10201304011203481429
  lora_path: "models/DreamBooth_LoRA/cyberpunk.safetensors"
  db_path: "models/DreamBooth_LoRA/rcnzCartoon3d_v20.safetensors"
  lora_alpha: 0.8