base: 'example/config/base.yaml'
prompts:
- - 1bear walking in a shop, best quality, 4k
n_prompt: 
  - 'wrong white balance, dark, sketches,worst quality,low quality, deformed, distorted, disfigured, bad eyes, wrong lips,weird mouth, bad teeth, mutated hands and fingers, bad anatomy,wrong anatomy, amputation, extra limb, missing limb, floating,limbs, disconnected limbs, mutation, ugly, disgusting, bad_pictures, negative_hand-neg'
validation_data:
  input_name: 'bear'
  validation_input_path: 'example/img'
  save_path: 'example/result'
  mask_sim_range: [0, 1, 2]
generate:
  use_lora: false
  use_db: true 
  global_seed: 10201034102130841429
  lora_path: "models/DreamBooth_LoRA/cyberpunk.safetensors"
  db_path: "models/DreamBooth_LoRA/rcnzCartoon3d_v20.safetensors"
  lora_alpha: 0.4