base: 'example/config/base.yaml'
prompts:
- - a golden labrador jump
  - a golden labrador walking
  - a golden labrador is running
n_prompt: 
  - 'collar, leashes, collars, wrong white balance, dark, sketches,worst quality,low quality, deformed, distorted, disfigured, bad eyes, wrong lips,weird mouth, bad teeth, mutated hands and fingers, bad anatomy,wrong anatomy, amputation, extra limb, missing limb, floating,limbs, disconnected limbs, mutation, ugly'
validation_data:
  input_name: 'labrador'
  validation_input_path: 'example/img'
  save_path: 'example/result'
  mask_sim_range: [0, 1, 2]
generate:
  use_lora: false
  use_db: true 
  global_seed: 4292543217695451000
  lora_path: ""
  db_path: "models/DreamBooth_LoRA/rcnzCartoon3d_v20.safetensors"
  lora_alpha: 0.8